baseURL = 'http://ruideabreu.github.io/'
title = 'Rui de Abreu'
theme = 'creative-portfolio'
languageCode = 'en-us'

[params]
  style = "red"
  description = "Describe your website"
  copyright = "&copy;2022 Rui de Abreu"
  sidebarAbout = [
    "I am a Lisbon based architect, graduated in 2004, specialized in renovations."
  ]
  email = 'f/xpzbvebv'

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
#  facebook      = "full page or profile url in facebook"
  email         = "hello@ruideabreu.com"
#  twitter       = "full profile url in twitter"
#  linkedin      = "full profile url in linkedin"
  instagram     = "https://www.instagram.com/ruideabreu/"
  